### ISSUE TITLE
Documentation - GPU-enabled ACI containers

### ISSUE THREAD

**Issue by MarcosMMartinez** [virtual-kubelet/virtual-kubelet#537]
---

### Documentation Request

https://github.com/virtual-kubelet/virtual-kubelet/tree/master/providers/azure 

Azure provider landing page for virtual kubelet shows GPU-enabled containers  currently have documentation pending? Do we have an ETA for available or perhaps this documentation is being curated elsewhere?

**Comment by snobu** [comment]
Until the docs are ready, a sample YAML that deploys a basic nvidia-smi pod would be tremendous.

**Comment by srrengar** [comment]
@MarcosMMartinez @snobu we are merging GPU support upstream from a private branch and will publish the docs shortly after. @VDuleb can you provide an estimate on when the ACI connector will support GPUs?

**Comment by wlodekb** [comment]
Any progress on that ?

**Comment by srrengar** [comment]
Yes this has been merged. If you are using the ACI connector without VNets then it should now work, but there is a known issue when using GPU and VNets together that we are investigating

**Comment by wlodekb** [comment]
Hi Stravan

Can you elaborate more on case with vnets ? It is part of my setup, so what is the issue (any link on GH) , and expected fix ?
thx/Wlodek

**Comment by michaelbpalmer** [comment]
@srrengar, do you have an ETA for a fix with the known issues of using GPU and VNets together? It appears that this still does not work (I see the same error that @wlodekb mentioned above).

**Comment by cpuguy83** [comment]
@ibabou

**Comment by lachie83** [comment]
Is this still an issue? If so, I would request you reopen under the provider repo - https://github.com/virtual-kubelet/azure-aci

**Comment by cpuguy83** [comment]
Agreed, let's move to azure-aci if it is still an issue.
